apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: my-endpoint
  
  labels:
    kubernetes.io/service-name: my-external-svc
addressType: IPv4
ports:
  - name: ssh
    protocol: TCP
    port: 22
endpoints:
  - addresses:
    - 54.78.243.111
   