apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: my-app
  name: my-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: web
        image: nginx