apiVersion: v1
kind: Pod
metadata:
  name: "backend"
  annotations:
    description: "backend service"
  labels:
    app.kubernetes.io/name: "backend"
    app.kubernetes.io/component: "service"
    app.kubernetes.io/version: "v1.0"
  # selector:
  #   matchLabels:
  #     app.kubernetes.io/name: "backend"
  #   matchexpressions:
  #    - {key: app.kubernetes.io/version, operator: In, values: ["v1.0", "v1.1", "v1.2"]}
spec:
  containers:
    - name: "backend"
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: "frontend"
  labels:
    app.kubernetes.io/name: "frontend"
    app.kubernetes.io/component: "service"
    app.kubernetes.io/version: "v1.0"
spec:
  containers:
  - name: "frontend"
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: "logging-servic"
  labels:
    app.kubernetes.io/name: "logging"
    app.kubernetes.io/component: "utility"
    app.kubernetes.io/version: "v2.0"
spec:
  containers:
  - name: "logging"
    image: alpine
    command: ["sh", "-c", "while true; do echo 'logging service is running'; sleep 3600;done"]
  
---
apiVersion: v1
kind: Pod
metadata:
  name: "monitoring"
  labels:
    app.kubernetes.io/name: "monitoring"
    app.kubernetes.io/component: "utility"
    app.kubernetes.io/version: "v1.1"
spec:
  containers:
  - name: "monitoring"
    image: alpine
    command: ["sh", "-c", "while true; do echo 'monitoring service is running'; sleep 3600;done"]
