apiVersion: v1
kind: Pod
metadata:
  name: demo-sidecar
spec:
  volumes:
    - name: emptydir-volume
      emptyDir: {}
    - name: nfs-volume
      nfs:
        server: 192.168.1.9
        path: /mnt/shared
  containers:
    - name: main-container
      image: nginx:alpine
      volumeMounts:
        - name: emptydir-volume
          mountPath: /usr/share/nginx/html
        - name: nfs-volume
          mountPath: /mnt/nfs
      resources:
        requests:
          cpu: 250m
          memory: 64Mi
        limits:
          cpu: "500m"
          memory: "128Mi"
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 10
      ports:
        - containerPort: 80
    - name: sidecar-container
      image:  busybox
      volumeMounts:
        - name: emptydir-volume
          mountPath: /mnt/shared
      command: ["/bin/sh", "-c", "while true; do echo $(date) ' - Sidecar logging'; sleep 5; done"]
      resources:
        requests:
          cpu: "100m"
          memory: "16Mi"
        limits:
          cpu: "200m"
          memory: "32Mi"
        
        
      
    